name: Release To Docker
on:
  push:
    branches: [ master ]

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: atguigu-question
  IMAGE: code-server

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
      - name: Build Extension
        run: |
          set -ex
          cd extensions/oj
          npm install
          npm install -g @vscode/vsce
          vsce package --allow-missing-repository
          cp oj-0.0.1.vsix ../../docker
      - name: Detect Date
        run: echo "VERSION=$(date +%F)" >>$GITHUB_ENV
      - name: Build Image
        run: |
          TAG=${VERSION}
          docker login \
            --username="${{ secrets.DOCKER_USERNAME }}" \
            --password="${{ secrets.DOCKER_PASSWORD }}" \
            ${REGISTRY}
          cd docker
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest