name: Release To Docker
on:
  push:
    branches: [ master ]

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: atguigu-question
  IMAGE: code-server

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
      - name: Build Extension
        run: |
          set -ex
          cd extensions/oj
          npm install
          npm install -g @vscode/vsce
          vsce package --allow-missing-repository
          cp oj-0.0.1.vsix ../../docker/extensions
      - name: Detect Date
        run: echo "VERSION=$(date +%F)" >>$GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          pull: true
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
